/* 연습문제 */
/* 계정 'exam_이니셜' 로 생성 후 해당 계정에서 진행.


테이블명 : MAJOR
1. MAJOR_NO (학과번호) : NUMBER - PK
2. MAJOR_NM (학과명) : VARCHAR2(100) - NOT NULL




테이블명 : STUDENT
1. STUDENT_ID (학번) : NUMBER - PK
2. STUDENT_NAME (이름) : VARCHAR2(20) - NOT NULL
3. GENDER (성별) : VARCHAR2(3) CHECK ('남' , '여')
4. BIRTH (생년월일 : 'YYYY-MM-DD '형식으로 작성) : DATE
5. MAJOR_NO (전공학과번호) : NUMBER - FK (부모키 삭제 시 자식키 NULL 로 변경)
*/


CREATE TABLE MAJOR(
    MAJOR_NO NUMBER CONSTRAINT PK_MAJOR_NO PRIMARY KEY,
    MAJOR_NM VARCHAR2(100) CONSTRAINT NN_MAJOR_NM NOT NULL
);

COMMENT ON COLUMN MAJOR.MAJOR_NO IS '학과번호';
COMMENT ON COLUMN MAJOR.MAJOR_NM IS '학과명';



CREATE TABLE STUDENT(
    STUDENT_ID NUMBER CONSTRAINT PK_STUDENT_ID PRIMARY KEY,
    STUDENT_NAME VARCHAR2(20) CONSTRAINT NN_STUDENT_NAME NOT NULL,
    GENDER VARCHAR2(3) CONSTRAINT CK_GENDER CHECK ( GENDER IN ('남', '여') ),
    BIRTH DATE,
    MAJOR_NO NUMBER,
	  CONSTRAINT FK_MAJOR_NO FOREIGN KEY(MAJOR_NO) REFERENCES MAJOR(MAJOR_NO)
);


COMMENT ON COLUMN STUDENT.STUDENT_ID IS '학번';
COMMENT ON COLUMN STUDENT.STUDENT_NAME IS '이름';
COMMENT ON COLUMN STUDENT.GENDER IS '성별';
COMMENT ON COLUMN STUDENT.BIRTH IS '생년월일';
COMMENT ON COLUMN STUDENT.MAJOR_NO IS '전공학과번호';


SELECT * FROM USER_CONSTRAINTS C1
JOIN USER_CONS_COLUMNS C2 USING(CONSTRAINT_NAME)
WHERE C1.TABLE_NAME = 'STUDENT';


-- 4. BIRTH (생년월일 : 'YYYY-MM-DD '형식으로 작성) : DATE
-- ALTER TABLE STUDENT ADD CONSTRAINT CK_BIRTH CHECK BIRTH = (TO_DATE(BIRTH, 'YYYY-MM-DD'));

-- 5. MAJOR_NO (전공학과번호) : NUMBER - FK (부모키 삭제 시 자식키 NULL 로 변경)
-- 실수로 테이블 생성 시 FOREIGN KEY 삭제 옵션을 넣지 않았음
ALTER TABLE STUDENT DROP CONSTRAINT FK_MAJOR_NO;
ALTER TABLE STUDENT ADD CONSTRAINT FK_MAJOR_NO FOREIGN KEY(MAJOR_NO) REFERENCES MAJOR ON DELETE SET NULL;
-- 기존 제약조건 삭제 후 추가


INSERT INTO MAJOR VALUES(1, '컴퓨터공학과');
INSERT INTO MAJOR VALUES(2, '경영학과');
INSERT INTO MAJOR VALUES(3, '화학공학과');
INSERT INTO MAJOR VALUES(4, '영어학과');
INSERT INTO MAJOR VALUES(5, '심리학과');


SELECT * FROM MAJOR;
SELECT * FROM STUDENT;

DELETE FROM STUDENT;
INSERT INTO STUDENT VALUES(2020, '김남자', '남', TRUNC(TO_DATE('2000-10-10', 'YYYY-MM-DD')), 5);
INSERT INTO STUDENT VALUES(2021, '박여자', '여', TO_DATE('2001-05-04', 'YYYY-MM-DD'), 4);
INSERT INTO STUDENT VALUES(2022, '최남자', '남', TO_DATE('2002-11-22', 'YYYY-MM-DD'), 3);
INSERT INTO STUDENT VALUES(2023, '신여자', '여', TO_DATE('2003-02-03', 'YYYY-MM-DD'), 2);
INSERT INTO STUDENT VALUES(2024, '홍남자', '남', TRUNC(TO_DATE('2004-04-06', 'YYYY-MM-DD')), 1);
INSERT INTO STUDENT VALUES(2025, '테스트', '남', '2024-10-10', 1);
INSERT INTO STUDENT VALUES(2026, '테스트2', '남', '20550909', 1);
INSERT INTO STUDENT VALUES(2027, '테스트2', '남', '93/09/09', 1);
INSERT INTO STUDENT VALUES(2030, '테스트4', '남', TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 1);


SELECT *
FROM STUDENT
NATURAL JOIN MAJOR;


ALTER TABLE MAJOR RENAME COLUMN MAJOR_NM TO MAJOR_NAME;